[package]
name = "elektronka_media_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventual = "0.1.7"
image = "0.24.4"
crossterm = "0.25.0"
rodio = "0.16.0"
dirs = "4.0.0"